baseURL = 'https://zwiftcrushindaddies.github.io/'
languageCode = 'en-us'
title = 'Zwift Crushin Daddies'
theme = "blackburn"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Roster"
    pre = "<i class='fa fa-users fa-fw'></i>"
    weight = 2
    identifier = "roster"
    url = "/roster/"
  [[menu.main]]
    name = "Tips and Info"
    pre = "<i class='fa fa-book-open fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Videos"
    pre = "<i class='fa fa-video fa-fw'></i>"
    weight = 3
    identifier = "videos"
    url = "/video/"